# This YAML file is for creating an environment using conda-store (https://conda.store/),
# an environment management tool integrated in Nebari.

name: nebari-big-data-tutorial
description: 'Environment for the Data of an Unusual Size tutorial'
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - ipykernel
  - panel
  - hvplot
  - geoviews
  - pyarrow
  - nebari-dask=2023.1.1
  - gcsfs
  - python-graphviz
  - ipycytoscape
  - ipywidgets=7.7.1
